### ISSUE TITLE
Support Ubuntu/debian/RHEL/CentOS

### ISSUE THREAD

**Issue by parberge** [cmacrae/ansible-couchpotato#1]
Hey,

I created a fork and rewrote it to work with Ubuntu/debian/RHEL/CentOS. The reason not doing a pull request is that I changed a lot, and I don't know if it makes sense to merge it.
Anyway, I just wanted to let you know this, and if you decide to support these distros you can clone my fork and use parts of it.

**Comment by cmacrae** [comment]
Hey, nice work :) Thanks for letting me know!
